# Generated by Django 3.1 on 2020-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Authors', models.CharField(max_length=100)),
                ('Rating', models.FloatField(max_length=3)),
                ('ISBN', models.FloatField(max_length=10)),
                ('ISBN13', models.FloatField(max_length=10)),
                ('Language', models.CharField(max_length=5)),
                ('Pages', models.IntegerField(blank=True, null=True)),
                ('Rating_Count', models.IntegerField()),
                ('Reviews_Count', models.IntegerField()),
                ('Published_Date', models.DateTimeField()),
                ('Publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
