# Generated by Django 3.1 on 2020-10-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Published_Date',
            field=models.CharField(max_length=20),
        ),
    ]
