# Generated by Django 3.1 on 2020-10-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201020_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN13',
            field=models.CharField(max_length=10),
        ),
    ]
